/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppReviewRouteImport } from './routes/_app/review'
import { Route as AppMyReviewsRouteImport } from './routes/_app/my-reviews'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppFeedRouteImport } from './routes/_app/feed'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppMyReviewsRoute = AppMyReviewsRouteImport.update({
  id: '/my-reviews',
  path: '/my-reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/feed': typeof AppFeedRoute
  '/home': typeof AppHomeRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/my-reviews': typeof AppMyReviewsRoute
  '/review': typeof AppReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/feed': typeof AppFeedRoute
  '/home': typeof AppHomeRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/my-reviews': typeof AppMyReviewsRoute
  '/review': typeof AppReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/my-reviews': typeof AppMyReviewsRoute
  '/_app/review': typeof AppReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/feed'
    | '/home'
    | '/leaderboard'
    | '/my-reviews'
    | '/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/feed'
    | '/home'
    | '/leaderboard'
    | '/my-reviews'
    | '/review'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/login'
    | '/_app/feed'
    | '/_app/home'
    | '/_app/leaderboard'
    | '/_app/my-reviews'
    | '/_app/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-reviews': {
      id: '/_app/my-reviews'
      path: '/my-reviews'
      fullPath: '/my-reviews'
      preLoaderRoute: typeof AppMyReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFeedRoute: typeof AppFeedRoute
  AppHomeRoute: typeof AppHomeRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMyReviewsRoute: typeof AppMyReviewsRoute
  AppReviewRoute: typeof AppReviewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFeedRoute: AppFeedRoute,
  AppHomeRoute: AppHomeRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMyReviewsRoute: AppMyReviewsRoute,
  AppReviewRoute: AppReviewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
